# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.cache/wt [current_project]
set_property parent.project_path H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo h:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/ALU.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/ALU_Control.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/Control.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/Data_Memory.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/EX.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/EX_MEM.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/Forward.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/Hazard.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/ID.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/ID_EX.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/IF.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/IF_ID.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/Instruction_Memory.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/MEM.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/MEM_WB.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/PC_Controller.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/Peripheral.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/Register_File.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/WB.v
  H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/sources_1/imports/code/CPU_Pipeline.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/constrs_1/new/cpu_pipeline.xdc
set_property used_in_implementation false [get_files H:/SoftWare/Vivado/Project/cpu_pipeline/cpu_pipeline.srcs/constrs_1/new/cpu_pipeline.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CPU_Pipeline -part xc7a35tcpg236-1 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU_Pipeline.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_Pipeline_utilization_synth.rpt -pb CPU_Pipeline_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
